### ISSUE TITLE
Configure Mongo Atlas DB

### ISSUE THREAD

**Issue by jhernandez50** [jhernandez50/Ticketsystem#8]

**Comment by soobin-lim** [comment]
Checking npm commands and testing..
* The `npm start` script: In production, we only run the back-end server, which will serve the built React application code as its front end.
    
* The `npm run develop` script: In development, we need to run both a back-end server and the React development server, so we use the `concurrently` library to execute two separate promises at the same time.

* The `npm install` script: Since our dependencies for the entire application exist in two smaller applications, we use this script to automatically install all of them at once.

* The `npm run seed` script: We can seed our database with data when we run this command.

* The `npm run build` script: When we deploy our application, we instruct the hosting service to execute the `build` command and build our production-ready React application."

**Comment by soobin-lim** [comment]
![image](https://user-images.githubusercontent.com/68568686/145509352-97d075a2-750d-47b5-9309-1bc70a96b1b8.png)
database name : ticketing-app
starter collection:  User

**Comment by soobin-lim** [comment]
test branch :  deployment_test_1

heroku address : (https://tecproject3.herokuapp.com/)

**Comment by soobin-lim** [comment]
mongodb+srv://project3:project3@cluster0.nkp7y.mongodb.net/ticketing-app?retryWrites=true&w=majority

MONGODB_URI

**Comment by soobin-lim** [comment]
![image](https://user-images.githubusercontent.com/68568686/145511641-4b83c22d-1995-45c6-b701-5f404faf010f.png)
![image](https://user-images.githubusercontent.com/68568686/145511663-dbec9ac1-d469-4a37-ba9e-f4176d69a403.png)
![image](https://user-images.githubusercontent.com/68568686/145511685-d99669a9-d4c0-4e29-89b3-cfef7c7991a1.png)

**Comment by soobin-lim** [comment]
> ![image](https://user-images.githubusercontent.com/68568686/145511641-4b83c22d-1995-45c6-b701-5f404faf010f.png) ![image](https://user-images.githubusercontent.com/68568686/145511663-dbec9ac1-d469-4a37-ba9e-f4176d69a403.png) ![image](https://user-images.githubusercontent.com/68568686/145511685-d99669a9-d4c0-4e29-89b3-cfef7c7991a1.png)

It builds well, and there is an issue in..

**Comment by soobin-lim** [comment]
![image](https://user-images.githubusercontent.com/68568686/145514766-51a82126-40fe-446a-9368-7d9278d68014.png)

Editing package.json of root folder.. it works good
"homepage": ".",
  "description": "",
  "proxy": "http://127.0.0.1:3001"

https://tecproject3.herokuapp.com/
